-- When the provider last returned this account in a pass that took its rows.
--
-- What this does NOT establish: that the rows were fresh. It catches an institution whose accounts
-- drop out of the response. If Bridge instead keeps returning a lapsed institution's accounts with
-- cached data, this advances through the outage and never fires; nothing here or in the tests shows
-- which Bridge does. The reauth message in the response is still triaged and recorded as
-- reauth_required on the run, which is what tells the owner in that case.
--
-- The SimpleFIN request is sized from the connection's last_synced_at, which every pass advances.
-- When one institution needs a fresh login its accounts drop out of the response while the others
-- keep syncing hourly, so after the owner logs back in the next request reached back an ordinary
-- 30 days and the outage's earlier rows were never asked for. Holding last_synced_at instead would
-- make the whole connection read stale while it is syncing fine, so the watermark has to be per
-- account: a pass that sees an account return after a longer absence asks once more, far enough
-- back to cover it.
--
-- No backfill. NULL means "not yet observed under this column", and a NULL account never widens a
-- request; the first pass after this migration stamps every account it sees.
ALTER TABLE accounts ADD COLUMN provider_seen_at TEXT;
