import type Database from 'better-sqlite3';
import { endOfMonth, format, startOfMonth } from 'date-fns';
import {
  excludedFromTotalsSql,
  expenseSideSql,
  incomeSideSql,
  spendAmountSql,
} from './transactionFilters';

/**
 * What the numbers in this database MEAN.
 *
 * `PRAGMA table_info` tells a model that `transactions.amount` is an INTEGER. It does not tell it
 * that the integer is cents, that a negative one means money left the account, that a positive one
 * inside an expense category is a refund rather than income, or that summing the column without
 * `excludedFromTotalsSql` counts the owner's own transfers as spending. Every one of those has
 * already produced a wrong number on a screen in this app; the advisor reported $1,695.00 of
 * spending where Reports reported $75.00 on the same data, and the difference was entirely which
 * rows each side thought counted.
 *
 * So this file is a dictionary, not a dump. It is versioned in the repo and read by
 * `describe_schema`, which composes it with the live column list so that nothing is described that
 * does not exist.
 *
 * TWO RULES HOLD IT HONEST.
 *
 * 1. The spend/income predicates are GENERATED by calling the real functions in
 *    `transactionFilters.ts`, never transcribed. A transcription drifts silently the first time the
 *    predicate changes, and the model would go on pasting the old text.
 * 2. Nothing here states a live figure. "2,412 of 2,579 rows have a NULL `category_source`" is true
 *    today and false after the next sync, so the doc states what NULL MEANS and the observed
 *    distribution is counted at call time from the database in front of it.
 */

/** Bump when a meaning changes, so a cached prompt prefix can be told the dictionary moved. */
export const SCHEMA_DOC_VERSION = 1;

export interface ColumnMeaning {
  /** What the stored number or string IS, in units. Short enough to read at a glance. */
  unit: string;
  /** Sign convention, NULL meaning, and anything that has already been read wrongly. */
  note?: string;
}

export interface TableMeaning {
  purpose: string;
  columns: Record<string, ColumnMeaning>;
}

const CENTS = 'integer cents (divide by 100 for dollars)';
const LOCAL_DATE = 'local calendar date, TEXT yyyy-MM-dd';
const UTC_TIMESTAMP = 'ISO 8601 UTC timestamp';
const FLAG = '0 or 1';

export const TABLE_MEANINGS: Record<string, TableMeaning> = {
  transactions: {
    purpose:
      'The ledger. One row per posted or pending movement on an account. Provider rows are never deleted (the next sync re-inserts them), so rows are flagged out of totals rather than removed.',
    columns: {
      amount: {
        unit: CENTS,
        note:
          'SIGNED. Negative means money LEFT the account, positive means money ARRIVED. A positive row sitting in an EXPENSE category is a refund and is NOT income: it nets that category down. Classify by category class first, then sum the signed amount, which is what expenseSideSql/incomeSideSql do.',
      },
      date: {
        unit: LOCAL_DATE,
        note: 'The date the owner sees. Local, so it does not agree with SQLite date(\'now\'), which is UTC.',
      },
      quantity: {
        unit: 'REAL count of units, NOT money',
        note:
          'EXCEPTION to the integer-cents rule, and it is not dollars either: it is the signed change in units of security_id. Never divide it by 100. NULL means the units of this row are unknown (every row written before migration 046, and every activity type this app does not import), not zero.',
      },
      security_id: {
        unit: 'securities.id, nullable',
        note: 'What quantity counts. NULL alongside a NULL quantity means the row has no unit record.',
      },
      pending: { unit: FLAG, note: 'A pending row can still change amount, date or merchant, and reconciliation ignores it.' },
      transfer_status: { unit: 'enum, see enums.transfer_status' },
      duplicate_status: { unit: 'enum, see enums.duplicate_status' },
      review_status: { unit: 'enum, see enums.review_status' },
      source_type: { unit: 'enum, see enums.source_type' },
      category_source: {
        unit: 'enum, see enums.category_source',
        note:
          'NULL is NOT zero and NOT "the machine did it". It means the row was categorized before provenance existed (migration 041) and nothing recorded who chose. Most of this ledger is in that state; call get_provenance_summary for the live split rather than assuming.',
      },
      category_action_id: {
        unit: 'advisor_actions.id, nullable',
        note: 'Set only while an AI action still owns the row. A hand edit clears it, so undo cannot reach back through a human decision.',
      },
      category_previous_id: { unit: 'categories.id, nullable', note: 'What the category was before the write that set category_source.' },
      manually_categorized: {
        unit: FLAG,
        note: 'The older marker, kept alongside category_source because a bulk re-check can clear one and not the other. Honour BOTH before overwriting a category.',
      },
      merchant_name: { unit: 'text, nullable', note: 'Cleaned name. Falls back to original_name when NULL.' },
      original_name: { unit: 'text', note: 'Exactly what the institution sent. Never rewritten.' },
      created_at: { unit: UTC_TIMESTAMP, note: 'When mizan first saw the row, not when the money moved.' },
      updated_at: { unit: UTC_TIMESTAMP },
    },
  },
  accounts: {
    purpose: 'One row per account, from SimpleFIN, Coinbase, or entered by hand.',
    columns: {
      current_balance: {
        unit: CENTS,
        note:
          'For an asset, what it holds. For a liability (is_liability = 1) it is the amount OWED, stored POSITIVE, and it is SUBTRACTED from net worth. It may legitimately be NEGATIVE, which means the card is in credit and the bank owes the owner money; that raises net worth. Never Math.abs it and never clamp it at zero.',
      },
      available_balance: { unit: CENTS, note: 'Nullable. Provider-reported, excludes holds; not every provider sends it.' },
      credit_limit: { unit: CENTS, note: 'Nullable, liabilities only.' },
      native_balance: {
        unit: 'REAL count of native-currency units, NOT money',
        note: 'For a crypto wallet this is coins, not dollars. current_balance is the dollar value of the same position.',
      },
      is_liability: { unit: FLAG, note: 'Drives the sign convention on current_balance above.' },
      is_hidden: { unit: FLAG, note: 'Hidden from the screens. Most services filter these out; say so if you include them.' },
      type: { unit: 'enum, see enums.account_type' },
      connection_type: { unit: 'enum, see enums.connection_type' },
      backfill_floor_date: {
        unit: 'local date, nullable',
        note: 'The earliest date this provider will serve. Absence of transactions before it is a limit of the feed, not evidence nothing happened.',
      },
    },
  },
  categories: {
    purpose: 'Two-level category tree. parent_id NULL is a top-level category.',
    columns: {
      is_income: { unit: FLAG, note: 'Marks the income side. incomeSideSql keys on this, not on the sign of the amount.' },
      is_investment: {
        unit: FLAG,
        note:
          'Investment and crypto flows. Excluded from expenses so moving $500 into a brokerage does not read as spending it. This is what neutralises the mis-signed Fidelity transfer rows in spend totals; excludedFromTotalsSql alone would let them through.',
      },
      is_system: { unit: FLAG, note: 'Built-in category, not created by the owner.' },
    },
  },
  budgets: {
    purpose: 'One monthly limit per category. Set by the owner, so never overwrite one without asking.',
    columns: {
      amount: { unit: CENTS, note: 'The current limit. A closed month is judged against the amount that was in force then, held in budget_rollover_ledger.' },
      rollover_balance: { unit: CENTS, note: 'Signed carry into the current month. Negative means the category is behind.' },
      rollover: { unit: FLAG },
    },
  },
  budget_rollover_ledger: {
    purpose: 'What each budget looked like in each closed month, so a past month stops being restated from today\'s limit.',
    columns: {
      month: { unit: 'TEXT yyyy-MM, local calendar month' },
      budget_amount: { unit: CENTS, note: 'The limit that was in force in that month, frozen. Not today\'s limit.' },
      actual_spend: { unit: CENTS, note: 'Re-derived on read, so a late transaction still reaches the month it belongs to.' },
      starting_rollover: { unit: CENTS },
      ending_rollover: { unit: CENTS },
      calculated_at: { unit: UTC_TIMESTAMP },
    },
  },
  goals: {
    purpose: 'Savings and debt targets the owner set.',
    columns: {
      target_amount: { unit: CENTS, note: 'A target the owner chose. Proposal-only for the AI: never write it directly.' },
      current_amount: { unit: CENTS },
      starting_amount: { unit: CENTS },
      target_date: { unit: 'local date, nullable' },
      is_archived: { unit: FLAG },
    },
  },
  holdings: {
    purpose: 'Current position per security per account, including crypto.',
    columns: {
      quantity: { unit: 'REAL share or coin count, NOT money' },
      institution_price: {
        unit: 'REAL DOLLARS PER UNIT, not cents',
        note: 'EXCEPTION to the integer-cents rule. Crypto spot prices live here too, and a $0.003 token rounded to whole cents is destroyed, which is why this column stayed REAL. Do not divide it by 100.',
      },
      institution_value: { unit: CENTS, note: 'Market value of the position. This one IS cents.' },
      cost_basis: { unit: CENTS, note: 'Provider-reported. NULL means unknown, not zero: a zero basis would make a cash sweep read as 100% profit (migration 043).' },
      manual_cost_basis: { unit: CENTS, note: 'Nullable owner override. Proposal-only for the AI.' },
    },
  },
  holdings_history: {
    purpose: 'One row per holding per day, written by the sync.',
    columns: {
      date: { unit: LOCAL_DATE },
      quantity: { unit: 'REAL unit count, NOT money' },
      institution_price: { unit: 'REAL DOLLARS PER UNIT, not cents', note: 'Same exception as holdings.institution_price.' },
      institution_value: { unit: CENTS },
      cost_basis: { unit: CENTS, note: 'NULL means unknown.' },
    },
  },
  securities: {
    purpose: 'Tickers and instrument metadata referenced by holdings and by transactions.security_id.',
    columns: { sector_source: { unit: 'text', note: 'Whether the sector was reported, inferred, or set by hand.' } },
  },
  net_worth_snapshots: {
    purpose: 'Net worth over time. Some rows are measured, some are reconstructed, and the difference is load-bearing.',
    columns: {
      date: { unit: LOCAL_DATE },
      net_worth: { unit: CENTS, note: 'total_assets minus total_liabilities.' },
      total_assets: { unit: CENTS },
      total_liabilities: { unit: CENTS, note: 'Positive amount owed. A card in credit reduces this and can only be read correctly if its negative balance is preserved.' },
      liquid_assets: { unit: CENTS, note: "Frozen from the ACCOUNT TYPES in force when the row was written, not the types in force now. An account retyped later does not move in these columns, so a row can be a genuine measurement and still split the same money differently from breakdown. On this ledger both Fidelity accounts were auto-typed checking before being corrected, so this column reads $0.00 on two measured days when the portfolio held $1,661.66. GET /api/reports/investments refuses to read it and derives the value from breakdown instead. Prefer breakdown for any split; quote these only as the row's own record of how it was classified at the time." },
      investment_assets: { unit: CENTS, note: "Frozen from the ACCOUNT TYPES in force when the row was written, not the types in force now. An account retyped later does not move in these columns, so a row can be a genuine measurement and still split the same money differently from breakdown. On this ledger both Fidelity accounts were auto-typed checking before being corrected, so this column reads $0.00 on two measured days when the portfolio held $1,661.66. GET /api/reports/investments refuses to read it and derives the value from breakdown instead. Prefer breakdown for any split; quote these only as the row's own record of how it was classified at the time." },
      crypto_assets: { unit: CENTS, note: "Frozen from the ACCOUNT TYPES in force when the row was written, not the types in force now. An account retyped later does not move in these columns, so a row can be a genuine measurement and still split the same money differently from breakdown. On this ledger both Fidelity accounts were auto-typed checking before being corrected, so this column reads $0.00 on two measured days when the portfolio held $1,661.66. GET /api/reports/investments refuses to read it and derives the value from breakdown instead. Prefer breakdown for any split; quote these only as the row's own record of how it was classified at the time." },
      breakdown: { unit: 'JSON TEXT, {account_id: balance in cents}' },
      is_estimated: {
        unit: FLAG,
        note:
          'A RECONSTRUCTION, not a measurement. 1 means the row was rebuilt by replaying transactions backwards off today\'s balances, so it cannot be evidence about the ledger it was derived from, and reconciliation deliberately ignores these rows. Say "estimated" when quoting one.',
      },
      covered_accounts: { unit: 'count', note: 'How many accounts the row could see. A drop in coverage moves net worth without any money moving.' },
      total_accounts: { unit: 'count' },
    },
  },
  merchant_rules: {
    purpose: 'Standing merchant-to-category mappings. Several can match one merchant; get_merchant_rules returns them in the order that decides.',
    columns: {
      pattern: { unit: 'text', note: 'Matched fuzzily, so a short pattern sweeps in more than it names.' },
      source: { unit: 'enum, see enums.merchant_rule_source' },
      retired_at: { unit: 'ISO UTC timestamp, nullable', note: 'Non-NULL means retired. Retired rules stay for the audit trail and must be filtered out when reasoning about what applies.' },
      action_id: { unit: 'advisor_actions.id, nullable' },
    },
  },
  merchant_rule_revisions: {
    purpose: 'Every create, recategorize, rename and retire of a merchant rule, so a rule change is never silent.',
    columns: { operation: { unit: 'enum, see enums.merchant_rule_operation' } },
  },
  transaction_category_revisions: {
    purpose: 'Per-row category history. What undo reads to restore the exact prior category and source of every row an action touched.',
    columns: {},
  },
  advisor_actions: {
    purpose: 'What the AI actually did. One row per applied action, each individually undoable.',
    columns: {
      source: { unit: 'enum, see enums.advisor_action_source' },
      payload: { unit: 'JSON TEXT', note: 'The applied write, in the same shape the draft carried.' },
      created_at: { unit: UTC_TIMESTAMP },
    },
  },
  advisor_drafts: {
    purpose: 'Proposals awaiting the owner. A draft is not a thing that happened.',
    columns: { status: { unit: 'enum, see enums.advisor_draft_status' } },
  },
  recurring_patterns: {
    purpose: 'Detected recurring bills and income.',
    columns: {
      average_amount: { unit: CENTS, note: 'For a variable series this is a MEDIAN, not a known figure. Do not quote it as exact when amount_variance is high.' },
      amount_variance: { unit: 'REAL ratio, not money' },
      next_expected: { unit: 'local date', note: 'A single stale date per pattern. buildRecurringForecast projects forward and honours skips, snoozes and overrides; this column does not.' },
      is_confirmed: { unit: FLAG, note: 'The owner said yes. Unconfirmed patterns are detections.' },
    },
  },
  recurring_occurrence_adjustments: {
    purpose: 'Per-occurrence skip, snooze and amount override on a recurring pattern.',
    columns: { adjusted_amount: { unit: CENTS }, action: { unit: 'enum, see enums.recurring_adjustment_action' } },
  },
  sync_runs: {
    purpose: 'One row per sync attempt, with per-stage detail in sync_run_items and per-row detail in sync_changes.',
    columns: {
      started_at: { unit: UTC_TIMESTAMP },
      completed_at: { unit: 'ISO UTC timestamp, nullable', note: 'NULL means the run never finished, which is different from failing.' },
      status: { unit: 'enum, see enums.sync_run_status' },
      transactions_modified: { unit: 'count', note: 'Rows whose provider values changed. A steady non-zero count every hour is a symptom, not normal.' },
    },
  },
  sync_run_items: { purpose: 'Per-provider stage of one sync run. A stage can fail without aborting the rest.', columns: {} },
  sync_changes: {
    purpose: 'Row-level record of what a sync changed, including any balance mizan adopted over the provider\'s own value.',
    columns: { description: { unit: 'text', note: 'Names both values when a stored balance disagreed with the provider.' } },
  },
  app_preferences: { purpose: 'Small key/value settings. value is a JSON TEXT blob.', columns: {} },
  conversations: { purpose: 'Advisor chat threads.', columns: {} },
  messages: { purpose: 'Advisor chat messages, keyed to conversations.', columns: {} },
  data_import_runs: { purpose: 'CSV imports: what file, how many rows, what was skipped.', columns: {} },
  simplefin_connections: { purpose: 'SimpleFIN connection state. Credentials are NOT here; they are encrypted outside the database.', columns: {} },
  coinbase_connections: { purpose: 'Coinbase connection state. Credentials are NOT here; they are encrypted outside the database.', columns: {} },
  schema_migrations: { purpose: 'Which migration files have been applied.', columns: {} },
};

export interface EnumMeaning {
  table: string;
  column: string;
  values: Record<string, string>;
  note?: string;
}

export const ENUM_MEANINGS: Record<string, EnumMeaning> = {
  transfer_status: {
    table: 'transactions',
    column: 'transfer_status',
    values: {
      none: 'Not a transfer between the owner\'s own accounts.',
      candidate: 'Detected as one leg of a transfer, not yet confirmed.',
      confirmed: 'Confirmed transfer leg.',
      dismissed: 'The owner said this is not a transfer.',
    },
    note: 'candidate AND confirmed are both excluded from spend and income. Counting a suspected transfer until it is confirmed would make totals jump as detection runs.',
  },
  duplicate_status: {
    table: 'transactions',
    column: 'duplicate_status',
    values: {
      none: 'Not flagged as a duplicate.',
      candidate: 'Suspected duplicate, unresolved. Still counts in totals.',
      confirmed: 'The owner confirmed it is a redundant copy. Excluded from totals.',
      dismissed: 'The owner said it is not a duplicate. Counts normally.',
    },
    note: 'Only confirmed is excluded. dismissed is a decision that the row is REAL, so excluding it would delete money the owner said was there.',
  },
  review_status: {
    table: 'transactions',
    column: 'review_status',
    values: {
      open: 'Not yet reviewed by the owner.',
      reviewed: 'The owner has looked at it.',
      dismissed: 'The owner cleared it from the review queue.',
    },
    note: 'Review state says nothing about whether the row counts. It never affects a total.',
  },
  source_type: {
    table: 'transactions',
    column: 'source_type',
    values: {
      simplefin: 'From the SimpleFIN bank aggregator.',
      coinbase: 'From Coinbase.',
      manual: 'Entered by the owner.',
      import: 'Loaded from a CSV the owner supplied.',
    },
  },
  category_source: {
    table: 'transactions',
    column: 'category_source',
    values: {
      human: 'The owner chose it. Never overwrite one of these.',
      rule: 'A merchant rule matched.',
      heuristic: 'The local text classifier guessed it, with no model call.',
      ai: 'A model-authored draft applied it, carrying its advisor_actions id.',
    },
    note:
      'NULL is the fifth state and the most common one: categorized before provenance existed (migration 041), with no record of who chose. NULL is not zero and does not mean the machine did it.',
  },
  connection_type: {
    table: 'accounts',
    column: 'connection_type',
    values: {
      simplefin: 'Synced from SimpleFIN, read-only.',
      coinbase: 'Synced from Coinbase.',
      manual: 'Maintained by the owner; nothing syncs it.',
    },
    note: 'Plaid and Teller were removed in migration 014 and are not coming back.',
  },
  account_type: {
    table: 'accounts',
    column: 'type',
    values: {
      checking: 'Asset.',
      savings: 'Asset.',
      cash: 'Asset.',
      credit: 'Liability. Balance is the amount owed, and can go negative when the card is in credit.',
      brokerage: 'Asset, MARKET-DRIVEN: its balance moves when prices move, with no transaction recording it.',
      ira_traditional: 'Asset, market-driven.',
      ira_roth: 'Asset, market-driven.',
      crypto_wallet: 'Asset, market-driven.',
      other: 'Asset.',
      closed: 'No longer active.',
    },
    note: 'On a market-driven account the ledger cannot explain the balance, so a residual there is a price move rather than a gap.',
  },
  merchant_rule_source: {
    table: 'merchant_rules',
    column: 'source',
    values: {
      human: 'The owner wrote it.',
      suggestion: 'The owner accepted a suggested rule. Ranks with human.',
      ai: 'A model proposed it. Ranks BELOW the owner\'s rules on every merchant they both match.',
    },
  },
  advisor_action_source: {
    table: 'advisor_actions',
    column: 'source',
    values: {
      worker_auto: 'Applied by the background pass or a chat tool inside the autonomous domain.',
      user_confirm: 'The owner confirmed a draft.',
    },
  },
  advisor_draft_status: {
    table: 'advisor_drafts',
    column: 'status',
    values: { open: 'Waiting on the owner.', confirmed: 'Applied.', dismissed: 'The owner declined it.' },
  },
  merchant_rule_operation: {
    table: 'merchant_rule_revisions',
    column: 'operation',
    values: {
      create: 'The rule was written.',
      recategorize: 'The rule was pointed at a different category.',
      rename: 'The pattern text changed, the category did not.',
      retire: 'The rule was retired. It still exists and applies to nothing.',
    },
  },
  recurring_adjustment_action: {
    table: 'recurring_occurrence_adjustments',
    column: 'action',
    values: {
      skip: 'This occurrence will not happen. The forecast drops it.',
      snooze: 'This occurrence moved to a later date.',
      adjust: 'This occurrence has a different amount than the pattern median.',
    },
  },
  sync_run_status: {
    table: 'sync_runs',
    column: 'status',
    values: {
      running: 'Still going, or the process died mid-run. A run with no completed_at never finished.',
      succeeded: 'Every stage completed.',
      partial: 'At least one provider stage failed while the rest completed. The ledger is incomplete, not wrong.',
      failed: 'The run did not complete.',
    },
  },
  sync_run_item_status: {
    table: 'sync_run_items',
    column: 'status',
    values: {
      running: 'Stage still going.',
      succeeded: 'Stage completed.',
      skipped: 'Stage had nothing to do, usually because the provider is not configured.',
      reauth_required: 'The provider needs the owner to reconnect. Nothing was fetched.',
      failed: 'Stage failed. Other stages still ran.',
    },
  },
};

/**
 * The three category trees Reports leaves out of spend and income entirely.
 *
 * `excludedFromTotalsSql` removes rows the OWNER resolved (transfers, confirmed duplicates), and
 * `expenseSideSql` removes investment-classed categories. Neither removes the transfer category
 * tree from a query that reaches it another way, and reporting.ts drops those roots with a
 * recursive CTE on top of both. Leaving it out of the worked example below made that example
 * disagree with the Reports page by $775.00 on the owner's own July, which is precisely the failure
 * this dictionary exists to stop.
 *
 * The root ids are duplicated from reporting.ts because they are private there. That duplication is
 * pinned by tests/schemaDoc.test.ts, which asserts the example returns the same figure as
 * `getSpendingReport` on a fixture carrying a transfer, a refund and an investment flow, so a
 * change to the report's scope fails rather than drifts.
 */
const REPORT_SCOPE_ROOT_IDS = ['cat_xfer', 'cat_inv', 'cat_crypto'];

const REPORT_SCOPE_CTE = [
  'WITH RECURSIVE excluded_report_categories(id) AS (',
  `  SELECT id FROM categories WHERE id IN (${REPORT_SCOPE_ROOT_IDS.map((id) => `'${id}'`).join(', ')})`,
  '  UNION ALL',
  '  SELECT c.id FROM categories c JOIN excluded_report_categories e ON c.parent_id = e.id',
  ')',
].join('\n');

const REPORT_SCOPE_CONDITION =
  '(t.category_id IS NULL OR t.category_id NOT IN (SELECT id FROM excluded_report_categories))';

/** The whole spend query, assembled from the same pieces, ready to paste. */
export function spendExampleSql(startDateLiteral: string, endDateLiteral: string): string {
  return [
    REPORT_SCOPE_CTE,
    `SELECT SUM(${spendAmountSql('t')}) AS spend_cents`,
    'FROM transactions t',
    'LEFT JOIN categories c ON c.id = t.category_id',
    `WHERE ${excludedFromTotalsSql('t')}`,
    `  AND ${REPORT_SCOPE_CONDITION}`,
    `  AND ${expenseSideSql('t', 'c')}`,
    '  AND t.pending = 0',
    `  AND t.date BETWEEN ${startDateLiteral} AND ${endDateLiteral}`,
  ].join('\n');
}

export interface TransactionReportInclusion {
  /** True when getSpendingReport and getCashflowReport count this row. */
  counts: boolean;
  /** Which side it lands on when it counts. Decided by category class, never by the sign. */
  side: 'expense' | 'income' | null;
  /** Empty when the row counts. Each entry names the predicate that dropped it, and the value that did. */
  excluded_because: string[];
}

interface InclusionRow {
  kept_by_resolution: number;
  in_report_scope: number;
  pending: number;
  expense_side: number;
  income_side: number;
  transfer_status: string | null;
  duplicate_status: string | null;
  category_id: string | null;
  is_investment: number | null;
  amount: number;
}

/**
 * Does the Reports page count this row?
 *
 * Answered by evaluating the SAME predicate strings this file publishes, against the row itself,
 * rather than by re-deciding it in TypeScript. `get_transaction_full` used to answer it with
 * `excludedFromTotalsSql`'s two flags alone, which omits both `pending = 0` and the recursive
 * cat_xfer / cat_inv / cat_crypto scope that reporting.ts applies on top of them.
 *
 * MEASURED, on a copy of the owner's database, over the 120 transactions dated 2026-07-01 to
 * 2026-07-31: the old two-flag test called 112 of them counted, this function calls 102, and the
 * ten it stops claiming are eight $100 Fidelity contributions in `cat_inv_transfer`, a $780 cash
 * deposit in `cat_xfer_in` and a $5.00 Venmo transfer in `cat_xfer_out`, every one of them sitting
 * at `transfer_status = 'none'`, which is the ordinary state before the pairing pass runs. Summing
 * the rows this function DOES count reproduces getSpendingReport's 78222 and getCashflowReport's
 * income of 217122 for that month exactly. A boolean handed to the model as fact has to be the
 * boolean the page uses.
 *
 * Null when no such row exists, so the caller says so rather than inventing an answer.
 */
export function transactionReportInclusion(
  db: Database.Database,
  transactionId: string
): TransactionReportInclusion | null {
  const row = db
    .prepare(
      `${REPORT_SCOPE_CTE}
       SELECT
         CASE WHEN ${excludedFromTotalsSql('t')} THEN 1 ELSE 0 END AS kept_by_resolution,
         CASE WHEN ${REPORT_SCOPE_CONDITION} THEN 1 ELSE 0 END AS in_report_scope,
         COALESCE(t.pending, 0) AS pending,
         CASE WHEN ${expenseSideSql('t', 'c')} THEN 1 ELSE 0 END AS expense_side,
         CASE WHEN ${incomeSideSql('t', 'c')} THEN 1 ELSE 0 END AS income_side,
         t.transfer_status, t.duplicate_status, t.category_id, t.amount,
         c.is_investment
       FROM transactions t
       LEFT JOIN categories c ON c.id = t.category_id
       WHERE t.id = ?`
    )
    .get(transactionId) as InclusionRow | undefined;
  if (!row) return null;

  const side = row.expense_side === 1 ? 'expense' : row.income_side === 1 ? 'income' : null;
  const counts =
    row.kept_by_resolution === 1 && row.in_report_scope === 1 && row.pending === 0 && side !== null;

  const excluded: string[] = [];
  if (row.pending === 1) {
    excluded.push('pending = 1: every report applies t.pending = 0, so a pending row counts nowhere until it posts.');
  }
  if (row.transfer_status === 'candidate' || row.transfer_status === 'confirmed') {
    excluded.push(
      `transfer_status = '${row.transfer_status}': excluded_from_totals drops both legs of a transfer, candidate as well as confirmed.`
    );
  }
  if (row.duplicate_status === 'confirmed') {
    excluded.push("duplicate_status = 'confirmed': excluded_from_totals drops a copy the owner resolved.");
  }
  if (row.in_report_scope === 0) {
    excluded.push(
      `category_id = '${String(row.category_id)}' sits inside the transfer, investment or crypto category tree (cat_xfer, cat_inv, cat_crypto and their children), which the reports drop wholesale, children included.`
    );
  }
  if (side === null) {
    excluded.push(
      row.is_investment === 1
        ? `category_id = '${String(row.category_id)}' is classed as an investment flow (categories.is_investment = 1), which expense_side excludes so moving money into a brokerage does not read as spending it.`
        : `neither income_side nor expense_side claims this row (category_id = ${String(row.category_id)}, amount = ${row.amount} cents), so it lands in no report total.`
    );
  }
  // The list is built from the same row the boolean is, but it is assembled by hand, so a silent
  // disagreement between "does not count" and "here is why" is possible. Say so rather than
  // returning an empty explanation for an excluded row.
  if (!counts && excluded.length === 0) {
    excluded.push('excluded by the report predicates, with no more specific reason available. See predicates.example.');
  }

  return { counts, side, excluded_because: excluded };
}

export interface SchemaDocColumn {
  name: string;
  type: string;
  unit?: string;
  note?: string;
}

/**
 * A table in the doc, at one of two levels of detail.
 *
 * The two levels are DIFFERENT SHAPES rather than the same shape with fields missing. A
 * `names_only` table is one whose meanings were not asked for, and if it carried an empty-noted
 * `columns` array it would be indistinguishable from a table nothing is documented about, which is
 * the same class of wrong reading this whole file exists to stop.
 */
export type SchemaDocTable =
  | { table: string; purpose: string | null; detail: 'full'; columns: SchemaDocColumn[] }
  | { table: string; purpose: string | null; detail: 'names_only'; column_names: string };

export interface SchemaDocEnum extends EnumMeaning {
  /** Value -> row count, counted from this database now. Absent when the table has no rows. */
  observed: Record<string, number>;
  /** Values present in the data with no documented meaning. Normally empty. */
  undocumented_values: string[];
}

export interface SchemaDoc {
  version: number;
  tables: SchemaDocTable[];
  /** Which tables came back expanded, and how to ask for the rest. */
  detail: {
    expanded: string[];
    note: string;
  };
  money: {
    rule: string;
    real_dollar_exceptions: string[];
    not_money: string[];
  };
  sign_conventions: string[];
  predicates: {
    usage: string;
    excluded_from_totals: string;
    income_side: string;
    expense_side: string;
    spend_amount: string;
    report_scope_cte: string;
    report_scope_condition: string;
    example: string;
    /** What date range `example` carries, so a pasted month is never assumed to be the one wanted. */
    example_range: string;
  };
  enums: Record<string, SchemaDocEnum>;
  time: {
    today_local: string;
    local_dates: string;
    utc_timestamps: string;
    warning: string;
  };
  reconstructions: string[];
}

const NULL_KEY = 'NULL';

/**
 * Live value distribution for one enum column.
 *
 * Counted rather than asserted: the point of the `category_source` entry is that most rows are
 * NULL, and a hardcoded number would be wrong by the next sync. Any value present in the data with
 * no documented meaning is surfaced instead of being quietly rendered as a bare string.
 */
function observeEnum(db: Database.Database, meaning: EnumMeaning): {
  observed: Record<string, number>;
  undocumented: string[];
} {
  const rows = db
    .prepare(
      `SELECT COALESCE(CAST("${meaning.column}" AS TEXT), '${NULL_KEY}') AS value, COUNT(*) AS n
       FROM "${meaning.table}" GROUP BY 1 ORDER BY 2 DESC`
    )
    .all() as Array<{ value: string; n: number }>;

  const observed: Record<string, number> = {};
  const undocumented: string[] = [];
  for (const row of rows) {
    observed[row.value] = row.n;
    if (row.value !== NULL_KEY && !(row.value in meaning.values)) undocumented.push(row.value);
  }
  return { observed, undocumented };
}

export interface ProvenanceSummary {
  total_transactions: number;
  categorized: number;
  uncategorized: number;
  by_source: Array<{ source: string; meaning: string; transactions: number }>;
  /** Rows an AI action still owns, so an undo can still put them back. */
  ai_rows_with_a_live_action: number;
  /** Rows the owner chose by hand, under either marker. These are never overwritten. */
  owner_chosen: number;
}

/**
 * Who chose the category on each row.
 *
 * The single most misread column in this schema. `category_source` is NULL on most of the ledger
 * because provenance only arrived in migration 041, and a model that reads NULL as zero concludes
 * the owner has categorized nothing, or that the machine did all of it. Both are wrong, and both
 * lead somewhere destructive: the second one invites a bulk re-categorization over the owner's own
 * decisions.
 *
 * Every figure here is counted from the database, never asserted.
 */
export function getCategoryProvenance(db: Database.Database): ProvenanceSummary {
  const totals = db
    .prepare(
      `SELECT COUNT(*) AS total,
              SUM(CASE WHEN category_id IS NOT NULL THEN 1 ELSE 0 END) AS categorized,
              SUM(CASE WHEN category_source = 'ai' AND category_action_id IS NOT NULL THEN 1 ELSE 0 END) AS ai_live,
              SUM(CASE WHEN manually_categorized = 1 OR category_source = 'human' THEN 1 ELSE 0 END) AS owner_chosen
       FROM transactions`
    )
    .get() as { total: number; categorized: number | null; ai_live: number | null; owner_chosen: number | null };

  const meanings = ENUM_MEANINGS.category_source.values;
  const bySource = (
    db
      .prepare(
        `SELECT COALESCE(category_source, '${NULL_KEY}') AS source, COUNT(*) AS n
         FROM transactions GROUP BY 1 ORDER BY 2 DESC`
      )
      .all() as Array<{ source: string; n: number }>
  ).map((row) => ({
    source: row.source,
    meaning:
      row.source === NULL_KEY
        ? 'Categorized before provenance existed (migration 041). Nothing recorded who chose. NOT zero, and NOT the machine.'
        : meanings[row.source] ?? 'Undocumented value; see services/schemaDoc.ts.',
    transactions: row.n,
  }));

  return {
    total_transactions: totals.total,
    categorized: totals.categorized ?? 0,
    uncategorized: totals.total - (totals.categorized ?? 0),
    by_source: bySource,
    ai_rows_with_a_live_action: totals.ai_live ?? 0,
    owner_chosen: totals.owner_chosen ?? 0,
  };
}

function liveTables(db: Database.Database): string[] {
  return (
    db
      .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
      .all() as Array<{ name: string }>
  ).map((row) => row.name);
}

function liveColumns(db: Database.Database, table: string): Array<{ name: string; type: string }> {
  return db.prepare(`PRAGMA table_info("${table.replace(/"/g, '""')}")`).all() as Array<{
    name: string;
    type: string;
  }>;
}

/**
 * The tables whose column meanings ship on every call, whatever was asked for.
 *
 * Every spend or income query reads all three, and the readings that have already produced a wrong
 * number on a screen here (cents, the refund sign, the transfer/investment category classes) live
 * on their columns. The other 26 tables are listed with their purpose and their column names, and
 * `describeTables` expands any of them on request.
 *
 * MEASURED, on a copy of the owner's database, as
 * `Buffer.byteLength(JSON.stringify(buildSchemaDoc(db)), 'utf8')`: expanding all 29 tables on every
 * call was 34,398 bytes, roughly 8.6k tokens, landing uncached inside a tool loop that runs up to 8
 * rounds. The core three plus the index is 25,507 bytes, and `describeTables(db, ['holdings'])` is
 * 1,622, so asking for one more table costs a twentieth of what carrying all of them did.
 */
const ALWAYS_DETAILED_TABLES = ['transactions', 'accounts', 'categories'];

function describeOneTable(db: Database.Database, table: string, full: boolean): SchemaDocTable {
  const meaning = TABLE_MEANINGS[table];
  const purpose = meaning?.purpose ?? null;
  const columns = liveColumns(db, table);
  if (!full) {
    return { table, purpose, detail: 'names_only', column_names: columns.map((c) => c.name).join(', ') };
  }
  return {
    table,
    purpose,
    detail: 'full',
    columns: columns.map((column) => {
      const columnMeaning = meaning?.columns[column.name];
      return {
        name: column.name,
        type: column.type || 'ANY',
        ...(columnMeaning ? { unit: columnMeaning.unit, note: columnMeaning.note } : {}),
      };
    }),
  };
}

export interface TableDetail {
  version: number;
  tables: SchemaDocTable[];
  /** Names that are not tables in this database. Reported rather than silently returning nothing. */
  requested_but_unknown: string[];
  note: string;
}

/**
 * Full column meanings for named tables, and nothing else.
 *
 * The expansion has to be CHEAP or it is not worth having: re-sending the predicates, the enum
 * distributions and the whole table index alongside one expanded table would cost more than the
 * fat default it is meant to replace. So this returns the tables asked for and says plainly that
 * the rest of the dictionary was not repeated, rather than leaving the model to assume either way.
 */
export function describeTables(db: Database.Database, requested: string[]): TableDetail {
  const live = new Set(liveTables(db));
  const known = requested.filter((table) => live.has(table));
  return {
    version: SCHEMA_DOC_VERSION,
    tables: known.map((table) => describeOneTable(db, table, true)),
    requested_but_unknown: requested.filter((table) => !live.has(table)),
    note:
      'Column meanings for the tables asked for. The money rules, sign conventions, spend and income predicates, enum meanings and today\'s local date are NOT repeated here: call describe_schema with no arguments to get them, and do that before writing a spend or income query.',
  };
}

/**
 * The dictionary, composed with the schema actually in front of us.
 *
 * Column lists come from the database, so no column is described that does not exist. Meanings come
 * from `TABLE_MEANINGS`, so a meaning for a column that was dropped simply never attaches. The
 * reverse direction (a documented column that vanished) is caught by tests/schemaDoc.test.ts
 * against the migrated schema, which is where a drift like that should be found.
 *
 * Every table is always LISTED with its purpose and its column names; `ALWAYS_DETAILED_TABLES` also
 * carry per-column units and notes, and each table says which it got.
 */
export function buildSchemaDoc(db: Database.Database, now: Date = new Date()): SchemaDoc {
  const live = liveTables(db);
  const expanded = ALWAYS_DETAILED_TABLES.filter((table) => live.includes(table));
  const tables: SchemaDocTable[] = live.map((table) => describeOneTable(db, table, expanded.includes(table)));

  const present = new Set(tables.map((t) => t.table));
  const enums: Record<string, SchemaDocEnum> = {};
  for (const [key, meaning] of Object.entries(ENUM_MEANINGS)) {
    if (!present.has(meaning.table)) continue;
    const { observed, undocumented } = observeEnum(db, meaning);
    enums[key] = { ...meaning, observed, undocumented_values: undocumented };
  }

  return {
    version: SCHEMA_DOC_VERSION,
    tables,
    detail: {
      expanded: [...expanded].sort(),
      note:
        'Every table in this database is listed above with its purpose and its column names. A table marked detail = "names_only" has had its per-column units and notes withheld to keep this payload small; that is NOT a statement that none are documented. Call describe_schema again with tables: ["holdings", "budgets"] to expand any of them, and do that before writing SQL against a table you have only seen the names of.',
    },
    money: {
      rule:
        'Every money TOTAL is an INTEGER number of CENTS. Divide by 100 for dollars, and do the dividing once, at the end, so intermediate sums stay exact.',
      real_dollar_exceptions: [
        'holdings.institution_price and holdings_history.institution_price are REAL DOLLARS PER UNIT, not cents. Crypto spot prices live here. Rounding a $0.003 token to whole cents destroys it, which is why these columns were left REAL. Do not divide them by 100.',
      ],
      not_money: [
        'transactions.quantity is a REAL count of units of transactions.security_id. Not cents, not dollars.',
        'holdings.quantity and holdings_history.quantity are REAL share or coin counts.',
        'accounts.native_balance is a REAL count of native-currency units (coins for a wallet), not a dollar figure.',
        'recurring_patterns.amount_variance is a REAL ratio.',
        'Every *_count, covered_accounts, total_accounts and transactions_* column on sync_runs is a plain count.',
      ],
    },
    sign_conventions: [
      'transactions.amount: negative means money LEFT the account, positive means it ARRIVED.',
      'A liability balance (accounts.is_liability = 1) is stored POSITIVE as the amount OWED and is SUBTRACTED from net worth. It may legitimately be NEGATIVE, which means the card is in credit and the bank owes the owner money, and that RAISES net worth. Never Math.abs it, never clamp it to zero, and read a negative one as "owes you", not "you owe".',
      'A refund is a POSITIVE amount inside an EXPENSE category. It is not income. It nets its own category down, so a category total can legitimately be negative in a month with large returns.',
      'A negative amount inside an INCOME category is a payroll correction, and it nets income down for the same reason.',
      'transactions.quantity is the signed change in units held: positive means units arrived. For a trade that is the OPPOSITE sign to amount, because a buy is money out and units in.',
      'Reconciliation expresses both sides as a movement in NET WORTH, so a liability\'s balance movement is negated before it is compared with the ledger.',
    ],
    predicates: {
      usage:
        'EVERY query that sums transactions as spend or income must apply excluded_from_totals, must decide the side with income_side / expense_side rather than by the sign of the amount, and must carry report_scope_cte plus report_scope_condition so the transfer, investment and crypto category trees stay out. The first four strings are generated from services/transactionFilters.ts, so they are exactly what the Reports page uses. Paste them; do not paraphrase them. Skipping them is how the advisor once reported $1,695.00 of spending against Reports\' $75.00 on the same data. When a figure simply has to match the Reports page, prefer the spending_by_category and monthly_cashflow tools over writing it yourself.',
      excluded_from_totals: excludedFromTotalsSql('t'),
      income_side: incomeSideSql('t', 'c'),
      expense_side: expenseSideSql('t', 'c'),
      spend_amount: spendAmountSql('t'),
      report_scope_cte: REPORT_SCOPE_CTE,
      report_scope_condition: REPORT_SCOPE_CONDITION,
      // Derived from the same `now` as time.today_local. Hardcoded literals made the example a
      // stale month sitting next to a correct date the moment the calendar turned over, on a doc
      // whose own text calls it ready to paste.
      example: spendExampleSql(
        `'${format(startOfMonth(now), 'yyyy-MM-dd')}'`,
        `'${format(endOfMonth(now), 'yyyy-MM-dd')}'`
      ),
      example_range: `The CURRENT local month, ${format(startOfMonth(now), 'yyyy-MM-dd')} to ${format(endOfMonth(now), 'yyyy-MM-dd')}. Swap both literals for the range you actually want.`,
    },
    enums,
    time: {
      today_local: format(now, 'yyyy-MM-dd'),
      local_dates:
        'transactions.date, net_worth_snapshots.date, holdings_history.date, goals.target_date and every other bare date column is a LOCAL calendar date, TEXT yyyy-MM-dd.',
      utc_timestamps: 'created_at, updated_at, started_at, completed_at, retired_at and calculated_at are ISO 8601 UTC timestamps.',
      warning:
        "SQLite's date('now') is UTC and DISAGREES with this app's local month boundaries, so it can put a transaction in the wrong month. Use the today_local literal above, and write date ranges as literals, instead of calling date('now').",
    },
    reconstructions: [
      'net_worth_snapshots with is_estimated = 1 are RECONSTRUCTED by replaying transactions backwards off current balances. They are not measurements and cannot be evidence about the ledger they came from. Reconciliation ignores them for exactly that reason. Say "estimated" when you quote one.',
      'The per-account daily balance series (services/balanceHistory.ts, GET /api/accounts/:id/balance-history) is DERIVED from the ledger the same way, except on the days that carry a recorded balance sheet. Where the derived line and a recorded balance disagree, the disagreement is the finding; neither side is automatically right.',
      'recurring_patterns.average_amount on a variable series is a median of past occurrences, and buildRecurringForecast marks those occurrences amount_varies. A forecast is not a fact.',
      'holdings.cost_basis is whatever the provider reported. NULL means unknown, and no cost basis is derived from the ledger in this app because the disposal history was never imported.',
    ],
  };
}
